title: Bruno Duaso

author:
  # Biographic information
  avatar           : "/assets/BrunoImage.png "
  name             : "Bruno Duaso"
  bio              : "Electronic Engineer"
  location         : "London, UK"
  employer         : "Imperial College London"
  email            : "brunoduaso@gmail.com" 

theme: jekyll-theme-minimal