title: Bruno Duaso
logo: /assets/BrunoImage.png 
description: >- # this means to ignore newlines until "baseurl:"
  Electronic and Information Engineer
  Imperial College London
show_downloads: true
theme: jekyll-theme-minimal